from config.catalog.bracket.bracket_materail import BracketMaterial, BracketSpecialType, BracketInstallType, \
    BracketVariant, BracketBaseType

CAKO150: dict[int, BracketMaterial] = {
    1252: BracketMaterial(
        code=1252,
        name="G3.0-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type = BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    1253: BracketMaterial(
        code=1253,
        name="G3.0-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    1254: BracketMaterial(
        code=1254,
        name="G3.5-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    1255: BracketMaterial(
        code=1255,
        name="G3.5-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    1328: BracketMaterial(
        code=1328,
        name="G3.0-F",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),

    1329: BracketMaterial(
        code=1329,
        name="G3.5-F",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),

    1250: BracketMaterial(
        code=1250,
        name="G2.1-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1251: BracketMaterial(
        code=1251,
        name="G2.1-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1327: BracketMaterial(
        code=1327,
        name="G2.1-F",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),

941: BracketMaterial(
        code=941,
        name="TN-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
942: BracketMaterial(
        code=942,
        name="TN-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1330: BracketMaterial(
        code=1330,
        name="TN-F",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
}