from config.catalog.bracket.bracket_materail import BracketMaterial, BracketSpecialType, BracketInstallType, \
    BracketVariant, BracketBaseType

CAKO250: dict[int, BracketMaterial] = {
    641: BracketMaterial(
        code=641,
        name="CAKO250-OPG-3.0-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type = BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    642: BracketMaterial(
        code=642,
        name="CAKO250-OPG-3.0-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    643: BracketMaterial(
        code=643,
        name="CAKO250-OPG-3.5-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    644: BracketMaterial(
        code=644,
        name="CAKO250-OPG-3.5-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    1284: BracketMaterial(
        code=1284,
        name="CAKO250-OPG-3.0-F(S)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.SHORT,
        gauge=3.0,
    ),
    1285: BracketMaterial(
        code=1285,
        name="CAKO250-OPG-3.0-F(L)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.LONG,
        gauge=3.0,
    ),
    1286: BracketMaterial(
        code=1286,
        name="CAKO250-OPG-3.5-F(S)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.SHORT,
        gauge=3.5,
    ),
    1287: BracketMaterial(
        code=1287,
        name="CAKO250-OPG-3.5-F(L)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.LONG,
        gauge=3.5,
    ),
    1296: BracketMaterial(
        code=1296,
        name="CAKO250-OPG-3.0-AJ-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    1297: BracketMaterial(
        code=1297,
        name="CAKO250-OPG-3.0-AJ-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.0,
    ),
    1298: BracketMaterial(
        code=1298,
        name="CAKO250-OPG-3.5-AJ-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    1299: BracketMaterial(
        code=1299,
        name="CAKO250-OPG-3.5-AJ-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=3.5,
    ),
    645: BracketMaterial(
        code=645,
        name="CAKO250-OPG-2.1-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
646: BracketMaterial(
        code=646,
        name="CAKO250-OPG-2.1-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1288: BracketMaterial(
        code=1288,
        name="CAKO250-OPG-2.1-F(S)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.SHORT,
        gauge=2.1,
    ),
1289: BracketMaterial(
        code=1289,
        name="CAKO250-OPG-2.1-F(L)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.NONE,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.LONG,
        gauge=2.1,
    ),
1323: BracketMaterial(
        code=1323,
        name="CAKO250-OPG-2.1-AJ-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1324: BracketMaterial(
        code=1324,
        name="CAKO250-OPG-2.1-AJ-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.OPG,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
647: BracketMaterial(
        code=647,
        name="CAKO250-TN-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.TN,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
648: BracketMaterial(
        code=648,
        name="CAKO250-TN-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.TN,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1290: BracketMaterial(
        code=1290,
        name="CAKO250-TN-F(S)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.TN,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.SHORT,
        gauge=2.1,
    ),
1291: BracketMaterial(
        code=1291,
        name="CAKO250-TN-F(L)",
        base_type=BracketBaseType.F,
        special_type=BracketSpecialType.TN,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.LONG,
        gauge=2.1,
    ),
1325: BracketMaterial(
        code=1325,
        name="CAKO250-TN-AJ-I",
        base_type=BracketBaseType.I,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
1326: BracketMaterial(
        code=1326,
        name="CAKO250-TN-AJ-O",
        base_type=BracketBaseType.O,
        special_type=BracketSpecialType.AJ,
        install_type=BracketInstallType.TN,
        variant=BracketVariant.NONE,
        gauge=2.1,
    ),
    }